POST http://localhost:3001/reports HTTP/1.1
content-type: application/json

{
  "title": "Broken streetlight",
  "description": "The streetlight on 5th Ave is out at night.",
  "is_public": true,
  "is_anon": false,
  "location": "5th Ave and Pine St",
  "severity": "medium",
  "report_categories_id": 1,
  "user_id": 1
}

###

GET http://localhost:3001/reports HTTP/1.1
