POST http://localhost:8080/users HTTP/1.1
content-type: application/json

{
    "Name":         "Loud Warga",
    "Email":        "loud_warga_1",
    "Password":     "penis"
}

###

POST http://localhost:8080/api/auth/register HTTP/1.1
content-type: application/json

{
    "Name":         "Loud Warga Two",
    "Email":        "loud_warga_2",
    "Password":     "penis"
}
		
###
POST http://localhost:8080/api/auth/login HTTP/1.1
content-type: application/json

{
    "Email":        "loud_warga_2",
    "Password":     "penis"
}

### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjcyMjg1MjksInJvbGUiOiIiLCJ1c2VyX2lkIjoxfQ.TU_Uuk8hkOY9sF7hOwn-6n_5a333VEgZR9Oyf83cbTU